### ISSUE TITLE
ModelInterface Jv calculated at wrist incorrect

### ISSUE THREAD

**Issue by danieltcai** [manips-sai-org/sai2-common#5] opened 2017-07-06 22:56 UTC
Calculating the Jv at the wrist point does not return a Jacobian with a last column of all zeros. Sometimes writes very large values to elements of the last column (e.g. 1e+180), causing programs to crash.

**Comment by mikael-jorda** [comment] 2017-07-29 02:11
I can't reproduce the issue. Can you send me the file you used when it happened?

**Comment by shameekganguly** [comment] 2017-09-28 23:30
@tmigimatsu said he found a fix for this. Can you push the patch, Toki? Thanks!

**Comment by tmigimatsu** [comment] 2017-09-29 02:54
@shameekganguly I don't recall ever having this issue or having a fix for it. Could it be that the Jacobian function was called for the second to last link, and that rbdl then only populated the Jacobian for the first n-1 columns?

**Comment by shameekganguly** [comment] 2017-09-29 06:01
Hmm, I thought this was the same issue where you had to change the order of including Eigen to avoid a conflict? What was the symptom for that?

**Comment by tmigimatsu** [comment] 2017-09-29 19:43
The symptom for that was Eigen segfaulting randomly on matrix multiplications. It behaved very much like a standard race condition/memory error, where simply rearranging lines of code changed whether it segfaulted or not. Somehow Chai3d's bundled version of Eigen was conflicting, so this issue was fixed by linking Eigen before Chai3d.

**Comment by shameekganguly** [comment] 2017-10-02 06:01
Ah, I see. Then that might indeed be a different issue. Will have to dig deeper into this one. Could you add your change regardless? Thanks!

**Comment by mikael-jorda** [comment] 2023-06-30 10:31
Probably an issue in initializing the Jacobian passed to the function incorrectly

**Closed by mikael-jorda** 2023-06-30 10:31 UTC
